#!/usr/bin/env python
# coding: utf-8

import pandas as pd

crontab_line = '%d * * * * %s %s %s # autogenerated web-server switcher'
preemption = 8 # switching time in minutes 

def join_tables(files):
    df = pd.DataFrame()

    for file in files:
        errors = pd.read_csv(file)
        name = errors.columns[1]
        errors = errors[errors.columns[1]].values.tolist()
        df[name] = errors
    return df

def select_server(row):
    for column in row.keys():
        if row[column] == 0:
            return column

def get_crontab(df, cmd):
    crontab = []
    cur = None
    begin = 0

    for min in df.index:
        srv = df.iloc[min]['server']
        if srv != cur:
            if cur:
                crontab.append(crontab_line % (min - preemption, cmd, cur, srv))
            cur = srv

    return crontab
                
if __name__ == '__main__':
    import sys
    
    if len(sys.argv) < 4:
        print("Usage: %s switch_cmd time_table1.csv time_table2.csv..." % sys.argv[0])
        sys.exit(-1)

    cmd = sys.argv[1]

    df = join_tables(sys.argv[2:])  
    df['server'] = df.apply(select_server, axis=1)
    print(df)
    ctab = get_crontab(df, cmd)
    list(map(lambda s: print(s), ctab))

